on:
  push:
    branches:
      - kschlobohm/load_test_changes
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Restore NuGet Packages
      run: nuget restore eShopModernizedMVCSolution\eShopModernizedMVC.sln
 
    - name: Build and Publish Web App
      run: msbuild eShopModernizedMVCSolution\src\eShopModernizedMVC\eShopModernizedMVC.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Find the artifact
      run: Get-ChildItem -Include *eShopModernizedMVC.dll -File -Recurse -ErrorAction SilentlyContinue

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: eShopModernizedMVCSolution\src\eShopModernizedMVC\bin\app.publish\


  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'keschlob-workshop-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .